export const FABRIC_STAGE_BACKGROUND = 'rgb(21, 20, 20)';

export const FABRIC_ITEM_DEFAULT_BORDER_COLOR = '#084272'
export const FABRIC_ITEM_DEFAULT_FILL_COLOR = '#084272'

export const FABRIC_ITEM_DEFAULT_WIDTH = 150
export const FABRIC_ITEM_DEFAULT_HEIGHT = 48